name: release

on:
  push:
    tags: ['v*.*.*'] # only a valid semver tag

jobs:
  release:
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      contents: read   # Required to checkout the code
      id-token: write  # Required for OIDC / PyPi Trusted Publishing

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set Up Python 3.10
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'
      - name: Install build tools
        run: make install-build
      - name: Install
        run: make install
      - name: Build
        run: make dist
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
